[package]
name = "config-type"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["vibeswap-types/std"]
ckb = ["dep:ckb-std", "vibeswap-types/no_std"]

[dependencies]
vibeswap-types = { path = "../../lib/types", default-features = false }
ckb-std = { workspace = true, optional = true }
