[package]
name = "pow-lock"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["vibeswap-pow/std", "vibeswap-types/std"]
ckb = ["dep:ckb-std", "vibeswap-pow/no_std", "vibeswap-types/no_std"]

[dependencies]
vibeswap-pow = { path = "../../lib/pow", default-features = false }
vibeswap-types = { path = "../../lib/types", default-features = false }
sha2 = { version = "0.10", default-features = false }
ckb-std = { workspace = true, optional = true }
